### ISSUE TITLE
Resolution Scaling bug

### ISSUE THREAD

**Issue by jaap15** [jaap15/Pokemon_Memory_Match_Game#2]
The Resolution scaling of the game doesn't work correctly if you click on the start menu of the game when you are in landscape. See attached image. @Dburris13 would you be able to look into this when you get some time?
![resolution_scaling_bug](https://cloud.githubusercontent.com/assets/20345088/18408778/dea50bc2-76fe-11e6-88a3-b27fc0b13f94.PNG)

**Comment by Dburris13** [comment]
Alright should be fixed, 
![image](https://cloud.githubusercontent.com/assets/21694795/18411841/2acdd1e0-7746-11e6-84a7-ea0b0b979be6.png)

This is how it looks loading from landscape.

**Comment by jaap15** [comment]
okay great, thanks
